### PR TITLE
Remove all selected applications

### LINKED ISSUE #1625: Remove all selected applications
### Suggested new feature or improvement

Currently, "Install applications" in setup flow provides a button for adding all available applications. It would be better to have an option to quickly remove all selected applications. So there should also be a "Remove all" button to clear the list of selected applications.

### Scenario

This feature will make it more convenient for users to manage their selections, especially in cases where they wish to start over with their selections. 
Users won't have to manually deselect each application one by one if they change their mind or want to start over.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by hamnarauf**
## Summary of the pull request
Implemented a "Remove All" button to clear all the selected applications in setup flow.

## References and relevant issues
 https://github.com/microsoft/devhome/issues/1625

## Detailed description of the pull request / Additional comments
1. Added "Remove all" button in UI
2. Implemented remove all functionality in `RemoveAllPackages` to clear all selected applications 
3. Ensured that the button is only enabled when at least one application is selected

## Validation steps performed
Dev Home (Dev) 2023-09-30 17-06-57_Trim (1)

## PR checklist
- [x] Closes #1625
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Comment by bbonaby** [comment]
@AmelBawa-msft figured I'd let you do a first pass on this? Do you think we need to involve Ian with this?

**Comment by AmelBawa-msft** [comment]
Adding @ianyyu to help review the suggested change. Note: we're removing the 'Add all' button soon as part of removing the carousel in app install page.

**Comment by cinnamon-msft** [comment]
I don't think we need a design pass here. I'd rather us get this merged in and do a design pass later :) @AmelBawa-msft @bbonaby

**Comment by crutkas** [comment]
I agree with @cinnamon-msft

**Review by EricJohnson327 — APPROVED** [review]

**Review by krschau — APPROVED** [review]
Approving pending @EricJohnson327's testing

**Pull request merged**
