### PR TITLE
WIP: Add disk usage widget

### PR DESCRIPTION
**Pull request by zanseb**
## Summary of the pull request

I noticed that there is no widget for disk usage, so I tried to add one.

image

## References and relevant issues

https://github.com/microsoft/devhome/issues/1085

### CODE REVIEW

**Comment by zanseb** [comment]
This widget is still a WIP. The missing points are:
* Widget Icon
* "Next Disk" Implementation

Let me know if this PR is welcome at the current stage of the project, otherwise feel free to close it :)

**Comment by MeikTranel** [comment]
Nothing but love for this PR but i feel like the whole `Next Disk` thing akin to the `Next GPU` looks hideous and is almost never what i want to click on a widget - i'd want to select the disk beforehand and then only change it using a configuration dialog of some sort - @cinnamon-msft is this just a temporary thing until a more fleshed out interface for widget configuration was designed or is this intentional? Ideally i'd like this to be configured in this dialog:
image

**Comment by niels9001** [comment]
> Nothing but love for this PR but i feel like the whole `Next Disk` thing akin to the `Next GPU` looks hideous and is almost never what i want to click on a widget - i'd want to select the disk beforehand and then only change it using a configuration dialog of some sort - @cinnamon-msft is this just a temporary thing until a more fleshed out interface for widget configuration was designed or is this intentional? Ideally i'd like this to be configured in this dialog: image

Yeah see your point.. Something like a [PipsPager](https://learn.microsoft.com/en-us/windows/apps/design/controls/pipspager#horizontal-pipspager-with-navigation-buttons)would be better but not sure if widgets support that. I guess not?

**Comment by zanseb** [comment]
Would it be possible to preview all possible instances of a resource, so that the user has the possibility to pin a specific instance?

E.g.
My PC has two drives C: and D:. When adding a widget, I could see the preview of both drives and could add a specific istance one or both instances of the widget.

**Comment by crutkas** [comment]
if this is a WIP, mind if i shift this to a draft?

**Comment by EdwinVD** [comment]
I've already created a Windows 11 widget called 'Hard Disk' that displays all the disks and network storage in a progress bar. In addition, there's another widget that shows different types of files with a colored progress bar. These widgets are available on the Microsoft Store.

Take a look!

Microsoft Store - Hard Disk:
https://apps.microsoft.com/store/detail/hard-disk/9NNCSN19QMCX?hl=en-us

**Comment by bbonaby** [comment]
@EricJohnson327  @krschau, and @crutkas / @cinnamon-msft do we still want this? If so, I can start a review.

**Comment by krschau** [comment]
Closing this after a long period of inactivity to clean up the repo a little bit. Happy to reopen if this PR is revisited!

**Pull request closed without merging**
