### PR TITLE
Add loading progress ring to the dashboard view while loading widgets

### PR DESCRIPTION
**Pull request by aksoftware98**
## Summary of the pull request
Add a loading progress ring control to the dashboard page while loading the widgets. Current Dashboard pages stays blank for a bit before rendering the widgets

Loading Progress for the Widgets

## References and relevant issues
Not sure if #595 is the same issue as in the code, I saw it's mentioned to add that in a TODO comment that references another closed issue and used this. as I think 595 is for the loading inside the widget itself but referenced that just in case. 

## Detailed description of the pull request / Additional comments
- Add the **ProgressRing** UI control to the _DashboardView.xaml_ 
- Set the **Visibility** property to **Visible** of the ProgressRing in the **OnLoaded()** in the code-behind file of _DashboardView.xaml_
- Set the **Visibility** property to **Collapsed** of the ProgressRing in the **OnLoaded()** in the code-behind file of _DashboardView.xaml_

## Validation steps performed
Manual testing 

## PR checklist
- [ ] Closes #xxx
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Comment by aksoftware98** [comment]
@microsoft-github-policy-service agree

**Comment by krschau** [comment]
This is awesome, thanks for submitting this PR! (By the way, you're correct that 595 was intended to mean loading inside the widget itself)

**Review by krschau — APPROVED** [review]

**Comment by aksoftware98** [comment]
> Excuse me for closing and re-opening this PR, I think I need to do it to get the new build checks working properly since it was opened before they were in place...

It's okay, the checks failed but my branch was a bit behind, I merged main and pushed again

**Comment by crutkas** [comment]
cycling PR to get check kicked off

**Pull request merged**
