### PR TITLE
Add General Feedback option

### LINKED ISSUE #1115: Extra feedback option
### Suggested new feature or improvement

An extra feedback option like "General feedback" or "Other".

### Scenario

To give feedback that doesn't categorize in the current options for giving feedback.

### Additional details

I connected my GitHub account and wanted to specify a folder on WSL as the destination. The feedback I actually wanted to give is to specify in the documentation that this isn't possible. Because I read it and watched several video's before hand, because I am using WSL. I was pretty bummed out to discover it didn't work after all that effort. I know Dev Drives don't work with WSL, but I absolutely expected this to work.

### PR DESCRIPTION
**Pull request by hamnarauf**
## Summary of the pull request
Added a new option to provide a "General Feedback" in Settings > Feedback section. This option will allow users to give feedback that doesn't categorize in the current options for giving feedback.

## References and relevant issues
https://github.com/microsoft/devhome/issues/1115

## Validation steps performed
Created an issue via "General Feedback" option:

general-feedback

image

image

## PR checklist
- [x] Closes #1115 
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Comment by krschau** [comment]
@cinnamon-msft I think we would need Design to weigh in on this, yeah?

**Comment by cinnamon-msft** [comment]
I don't think we should hold this on design - this looks good to me and we can always tweak it after design gets a chance to look at it :)

**Review by cinnamon-msft — APPROVED** [review]

**Review by EricJohnson327 — APPROVED** [review]

**Review by krschau — CHANGES_REQUESTED** [review]
Hey @hamnarauf I'm sorry to ask this of you, but we discussed this issue and we'd like to pivot from a "General Feedback" option to exposing the "Documentation issue" type that is available in the GitHub website, but isn't available in Dev Home.

The issue template is here: https://github.com/microsoft/devhome/issues/new?assignees=&labels=Issue-Docs&projects=&template=Documentation_Issue.yml

If you don't mind changing your PR to implement this instead, I think the only work needed is updating the strings that are displayed and some variable names.

Thank you so much for your contribution, and I'm sorry it took us a while to get back to you!

**Comment by hamnarauf** [comment]
> Hey @hamnarauf I'm sorry to ask this of you, but we discussed this issue and we'd like to pivot from a "General Feedback" option to exposing the "Documentation issue" type that is available in the GitHub website, but isn't available in Dev Home.
> 
> The issue template is here: [microsoft/devhome/issues/new?assignees=&labels=Issue-Docs&projects=&template=Documentation_Issue.yml](https://github.com/microsoft/devhome/issues/new?assignees=&labels=Issue-Docs&projects=&template=Documentation_Issue.yml)
> 
> If you don't mind changing your PR to implement this instead, I think the only work needed is updating the strings that are displayed and some variable names.
> 
> Thank you so much for your contribution, and I'm sorry it took us a while to get back to you!

Alright, since this one got prematurely merged, I'll open a new PR supporting "Documentation" issue.

**Pull request merged**
