### PR TITLE
Flatten directory structure, consistent file names

### PR DESCRIPTION
**Pull request by mattwojo**
## Summary of the pull request

Flattens the directory structure for sample configuration files and changes file names to be consistent casing and structure.

## References and relevant issues

Currently directories are nested for no apparent reason (?). File names are inconsistent. Casing is inconsistent.

## Detailed description of the pull request / Additional comments

No change to actual file content, only file names and directory structure. 

## PR checklist

None of these are applicable. 

- [ ] Closes #xxx
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Comment by bbonaby** [comment]
Thanks @mattwojo , 

@denelon  I vaguely remember the structure might be like this for standardization reasons? Where the file name is  configuration.dsc.yaml ? But I may be wrong wrong in assuming that. @ryfu-msft  added these months ago so maybe he'd know if its ok to rename these. Thanks!

**Review by krschau — CHANGES_REQUESTED** [review]
Please undo all the line ending whitespace changes.

**Comment by mattwojo** [comment]
@krschau - Could you explain what you mean by "line ending whitespace changes"? This PR is to make the folder structure and file naming more consistent... I don't believe there is anything to do with line ending whitespace.

**Comment by mattwojo** [comment]
Current sampleConfiguration directory structure (not consistent and unnecessary nesting):
image


My PR to update the directory structure:
image

**Comment by denelon** [comment]
The subdirectory structure for many of these was intentional to match the GitHub <organization>/<project> structure and to match their casing. The Windows directory was intended to mirror the dev environments for https://learn.microsoft.com/en-us/windows/dev-environment/#development-paths

**Comment by mattwojo** [comment]
I don't think that mirroring the dev environment directory structure is a good user experience and this PR is proposing that the directory be flattened for simplicity of use, clarity of what samples are available, and easier discoverability.

**Comment by mattwojo** [comment]
In regard to naming, do all WinGet configuration files need to be named "configuration.dsc"? This PR also changes file names to use a naming pattern like "aspnet-install-on-windows.dsc" ...so if this sort of file naming is not supported, do not merge this PR. I can file a separate PR that only flattens sampleConfiguration directory structure.

**Comment by denelon** [comment]
Technically, no. The files could be named anything. The convention for Git repositories is "./configurations/configuration.dsc.yaml" for the default configuration. Until those other projects and/or more GitHub projects have WinGet configuration files, these samples were just a starting place.

I think we should be intentional regarding any restructuring here. I also think the readme needs some help to stay consistent. If you think it would be better, I could see a GitHub directory with configurations named as organization.project.dsc.yaml with information helping to disambiguate what they were designed for. 

Then we could have a directory for the development paths and name those with a convention that makes sense.

Other examples could be named differently. We recently had some questions about samples of installing packages from the "msstore" source, and how to do uninstalls using "ensure: absent".

**Comment by krschau** [comment]
> @krschau - Could you explain what you mean by "line ending whitespace changes"? This PR is to make the folder structure and file naming more consistent... I don't believe there is anything to do with line ending whitespace.

@mattwojo If you look at the [file diff](https://github.com/microsoft/devhome/pull/1586/files?diff=split&w=0) without hiding whitespace, you'll see that almost every line has been changed. I'm 99% sure this is the line endings getting changed. I'm sorry it's annoying, we haven't added a .gitattributes that convers this directory yet (I've been fixing this up piecemeal to try to avoid huge, bothersome merge conflicts).

**Comment by mattwojo** [comment]
@krschau - the diff looks that way because this PR changes directory structure, not a whitespace issue. I didn't change anything in the actual files. 
@denelon - agree about some intentional restructuring. If we're going to invest in offering Configurations here, we should be forward thinking as the number has the potential to grow quickly. Let's share a call sometime soon.

**Comment by krschau** [comment]
> @krschau - the diff looks that way because this PR changes directory structure, not a whitespace issue. I didn't change anything in the actual files.

I was finally able to double check (having internet issues today), and this change does switch most line endings from Windows (crlf) to unix (lf). If it was just the rename it would say so in the GitHub diff view.

**Comment by mattwojo** [comment]
Ahh- I see, it's the line ending default that I have selected for Git. I can switch that. I'll talk with Demitrius about what sort of directory structure file naming makes the most sense and whether to fix this PR or file a new one.

**Comment by krschau** [comment]
Closing due to inactivity. Please feel free to open it back up with this work comes back around.

**Comment by denelon** [comment]
@mattwojo there is another PR on moving the files, and @RDMacLachlan already implemented a new structure full of README.md files for the SampleConfigurations.

**Pull request closed without merging**
