### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jorgelevy**
Updating Twitter handler for clintrutkas

### CODE REVIEW

**Review by cinnamon-msft — APPROVED** [review]
Great catch! Thank you!

**Comment by Aaron-Junker** [comment]
Wouldn't it make more sense to link the GitHub handles?

**Comment by jorgelevy** [comment]
> Wouldn't it make more sense to link the GitHub handles?

It could be the 2 handlers. I was looking to follow people on the project and Twitter handlers were exactly what I was looking, and GitHub handles make sense since the project is in GitHub.

**Comment by jorgelevy** [comment]
GitHub handlers added to the PR

**Review by wolf99 — APPROVED** [review]

**Comment by crutkas** [comment]
need to close / reopen to get the checks to run with the new system.

**Pull request merged**
