### PR TITLE
Move 'Feedback' row lower on the Settings page

### LINKED ISSUE #1956: Move the Feedback row in the Settings page to the bottom
### Suggested new feature or improvement

Can you make the 'Feedback' column the last column? 

image

### Scenario

Before the previous update the 'Feedback' column was the last.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by gregalantiu2**
## Summary of the pull request
Request was made and agreed upon for the "Feedback" row to be moved to the bottom of the Settings view. This simple PR makes that change. 

## References and relevant issues
#1956 

## Detailed description of the pull request / Additional comments
The SettingsViewModel class that populates that view has an array of Setting objects. I moved the "Feedback" Setting object to the end of the array which renders it last. 

## Validation steps performed
Manually verified UI renders the "Feedback" row last.
image

## PR checklist
- [x] Closes #1956 
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Comment by gregalantiu2** [comment]
This is my first time contributing to any open source project. Please let me know if I am missing anything or need to amend something. Thanks!

**Comment by crutkas** [comment]
LOVE IT!

**Review by krschau — CHANGES_REQUESTED** [review]
Temporarily blocking this since it's going to conflict with #2104. I think once that one goes in, we should make the "Feedback" item the second-to-last one.

**Review by krschau — APPROVED** [review]

**Review by EricJohnson327 — APPROVED** [review]

**Comment by skanda890** [comment]
Nice! It works.

**Pull request merged**
