### PR TITLE
Allow SSH widget to show entries with multiple Host aliases

### LINKED ISSUE #2646: SSH widget does not show hosts with multi-word alias names
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631.3447

### Other software

OS Build Version: 10.0.22631.3447.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

1. Point the SSH widget to a config file where one of the hosts has a multi-word alias name
3. See that that host is not shown in the list

### Expected result

The presence of the new configuration in the list

### Actual result

The application ignores the configuration

### Included System Information

CPU: AMD Ryzen 5 3600 6-Core Processor              
Physical Memory: 63.92GB (49.35GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.456.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

### PR DESCRIPTION
**Pull request by Gohellp**
## Summary of the pull request

Changes to Regexp to support writing from multiple Host aliases

## References and relevant issues
#2646 

## PR checklist
- [ ] Closes #2646
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Comment by krschau** [comment]
As part of this, it would be great if you could update our sample config (https://github.com/microsoft/devhome/blob/main/extensions/CoreWidgetProvider/Widgets/Assets/example_config) to include the kind of host you're fixing this for.

**Comment by Gohellp** [comment]
@microsoft-github-policy-service agree

**Comment by krschau** [comment]
Adding "do-not-merge" while I check something on our end.

**Review by krschau — APPROVED** [review]

**Comment by EricJohnson327** [comment]
Closing and reopening to try to trigger builds.

**Pull request merged**
