### PR TITLE
Align scan mode and non-scan mode navigation experience in the setup flow main page

### PR DESCRIPTION
**Pull request by AmelBawa-msft**
## Summary of the pull request
- By default, in non-scan mode, the narrator would say "More button" when navigating the setup flow main page using the keyboard Tab key.
- 'More' is the default value for the ActionIcon tooltip: [SettingsCards.cs](https://github.com/CommunityToolkit/Windows/blob/3c888a3178774c8b046200e0bf9c5ac4f9a22e24/components/SettingsControls/src/SettingsCard/SettingsCard.Properties.cs#L52C17-L52C17)
- Updated the code so the narrator mentions the button's header name instead: e.g. 'Configuration file button'

## References and relevant issues
Item number: 45056939

## PR checklist
- [ ] Closes #xxx
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Comment by krschau** [comment]
Why would these be limited to the Raw tree? Aren't they Controls? I'd expect that to change what narrator reads, we'd add the AutomationProperties.Name property?

**Review by dhoehna — APPROVED** [review]

**Review by krschau — CHANGES_REQUESTED** [review]
Just blocking to make sure my comment is considered.

**Comment by AmelBawa-msft** [comment]
> Why would these be limited to the Raw tree? Aren't they Controls? I'd expect that to change what narrator reads, we'd add the AutomationProperties.Name property?

@krschau, the keyboard navigation will focus on the action button inside the `SettingsCard`, not sure if that's why the `AccessibilityProperties.Name` is being ignored by the narrator? By default, the narrator will say "{Button.Header} group {ActionToolTip} button". Settings the `AccessibilityView` to `Raw` (or `Control` as suggested) allows the narrator to just say `{ActionToolTip} button` which is what I am aiming for in this change. Let me know if you have any suggestions I can try.

**Comment by krschau** [comment]
@AmelBawa-msft Ok, I think I get what's going on with the tooltip. If setting AccessibilityView to Control does result in the behavior we want, I would do that -- it seems more correct from what I understand about UIA.

**Review by krschau — APPROVED** [review]

**Pull request merged**
