### PR TITLE
Adding "open new window" icon to "Create Dev Drive" button (#1334)

### LINKED ISSUE #1334: Clarify information and behavior of Dev Drive card on "Introducing Dev Home" page
### Suggested new feature or improvement

When clicking the "Create Dev Drive" button is not clear to the user that they will be leaving Dev Home.

### Scenario

User is on the "Introducing Dev Home" page and sees the card for Dev Drive there is no indication that another app will be opened.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by gregalantiu2**
## Summary of the pull request
A request was made to clarify that clicking the "Create Dev Drive" button in the "Introducing Dev Home" page view takes you outside the app. @cinnamon-msft  suggested that the same icon used in the "Machine Configuration" page should be added to convey this idea.

## References and relevant issues
#1334 

## Detailed description of the pull request / Additional comments
In WhatsNewPage.xaml, some refactoring of the button element occurs. Child elements are added in order to accommodate both text and icon inside the button.

Additionally, I added a boolean property to the WhatsNewCard.cs called ShouldShowIcon which is used to toggle the Visibility property of the icon since currently the "Create Dev Drive" button is the only button we want the icon showing for. 

In WhatsNewPage.xaml.cs, logic was added to set ShouldShowIcon to false except for the "Create Dev Drive" button.

## Validation steps performed
Manually verified UI renders as expected
image

## PR checklist
- [x] Closes #1334 
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Comment by gregalantiu2** [comment]
> @gregalantiu2 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by gregalantiu2** [comment]
Hi @cinnamon-msft , does the image of the updated button look good (spacing, size, location, etc.)? If so, I'll publish this PR. Thanks!

**Comment by cinnamon-msft** [comment]
I would suggest making the icon a bit smaller to match the font size, but otherwise I think this looks great!

**Comment by gregalantiu2** [comment]
image

Yea, that's a great idea. Here it is smaller - more than happy to make more adjustments, just let me know 😄

**Review by EricJohnson327 — APPROVED** [review]

**Review by vineeththomasalex — APPROVED** [review]
LGTM!

**Pull request merged**
