### PR TITLE
fix: settings/DevHome.Settings.UnitTest/DevHome.SetupFlow.UnitTest.cs... as it fixes vulnerabilities.

### LINKED ISSUE #2587: Fix vulnerabilities.

### LINKED ISSUE #2597: DevHome Hyper-V Create: Hitting back requires that i retype name
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

Create a new Hyper V
Type in the required name.
Hit Next to go to summary or completion page.
Hit Back.

Notice your name is lost. :( 

### Expected result

Expect when I return that the name is restored so i can tweak it

### Actual result

The Name control is empty.

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by skanda890**
## Summary of the pull request
This PR is used to fix vulnerabilities.
## References and relevant issues
This closes #2587.
## PR checklist
- [X] Closes #2597
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Comment by skanda890** [comment]
I think this PR was created by accident.

**Review by skanda890 — COMMENTED** [review]
I think this must be correct if the version has MSTest.TestAdapter version 3.2.2 and MSTest.TestFramework version 3.2.2.

**Review by krschau — CHANGES_REQUESTED** [review]
It isn't a good idea to only update the versions in one project, while leaving the older versions in the other projects. We also are currently in stabilization week for the 0.13 release, so unless there is an immediate need to update versions, we can't take this.

**Comment by skanda890** [comment]
Can you update the older versions and tell me when

**Pull request closed without merging**
