### PR TITLE
Fix margin for NoAvailableExtensions

### LINKED ISSUE #1609: Incorrect margin for "No more extensions are available"
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2283

### Other software

_No response_

### Steps to reproduce the bug

1. Navigate to extensions library
2. Scroll down to the "Available in Microsoft Store" section
3. Get all available extensions
4. Examine the help text when no more extensions are available

### Expected result

The help text should have some margin below it.

### Actual result

image

No margin below help text.

### Included System Information

Windows: Windows.Desktop v10.0.22621.2283
System Architecture: X64

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by hamnarauf**
## Summary of the pull request
Adjust margin.

## References and relevant issues
https://github.com/microsoft/devhome/issues/1609

## Validation steps performed
image

## PR checklist
- [x] Closes #1609
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Comment by krschau** [comment]
Good catch! Thanks!

**Review by krschau — APPROVED** [review]

**Review by krschau — COMMENTED** [review]
Actually, I don't think 50 was the correct top margin. I'm looking at the design spec now to see what these numbers should be.

**Review by krschau — CHANGES_REQUESTED** [review]
Looks like the proper amount of space between the header and the NoAvailableExtensions message should be 36 pixels. We're already getting 16 pixels of margin from the header itself, so could you make this margin "0,20,0,48"?

**Comment by hamnarauf** [comment]
> Looks like the proper amount of space between the header and the NoAvailableExtensions message should be 36 pixels. We're already getting 16 pixels of margin from the header itself, so could you make this margin "0,20,0,48"?

Done

**Review by krschau — APPROVED** [review]

**Review by bbonaby — APPROVED** [review]

**Pull request merged**
